return {
	settings = {
		gopls = {
			gofumpt = true,
			codelenses = {
				gc_details = false,
				generate = true,
				regenerate_cgo = true,
				run_govulncheck = true,
				test = true,
				tidy = true,
				upgrade_dependency = true,
				vendor = true,
			},
			hints = {
				assignVariableTypes = true,
				compositeLiteralFields = true,
				compositeLiteralTypes = true,
				constantValues = true,
				functionTypeParameters = true,
				parameterNames = true,
				rangeVariableTypes = true,
			},
			analyses = {
				nilness = true,
				unusedparams = true,
				unusedwrite = true,
				useany = true,
				shadow = false,
				ST1003 = false,
			},
			staticcheck = true,
			directoryFilters = { "-.git", "-.vscode", "-.idea", "-.venv", "-node_modules" },
			semanticTokens = false,
			usePlaceholders = true,
			completeUnimported = true,
			experimentalPostfixCompletions = true,
		},
	},
}
