[Service]
ExecStart=
ExecStart=/usr/bin/earlyoom -r 3600 -n -m 10,5 -s 30,20 --avoid '(^|/)(init|systemd|sshd|Hyprland|hyprd|hyprpaper|xdg-desktop-portal-hyprland|eww|eww-bar)$$' --prefer '(^|/)(node|gopls|.*-language-server.*|tsserver|rust-analyzer|electron|chromium|mpvpaper)$$'
