#!/usr/sbin/nft -f

destroy table inet dotfiles_filter

table inet dotfiles_filter {
    chain input {
        type filter hook input priority filter; policy accept;

        iifname "lo" tcp dport 22 accept
        iifname "tailscale0" tcp dport 22 accept
        tcp dport 22 drop
    }
}
