windows:
  - today
  - workspaces
  - computer
  - music
  - player
weather:
  api_key_file: "~/.local/.owm_api_key"
  poll_interval: 1h
timer:
  default_minutes: 90
  default_alarm_hours: 6
  min_alarm_hours: 3
audio:
  source_max: 100
  sink_max: 100
  volume_step: 10
  default_sink_volume: 69
  default_source_volume: 100
  name_mappings:
    AirPodsHiRes: AirPods Max
    alsa_input.usb-Focusrite_Scarlett_Solo_USB_Y70ZEU921E21FF-00.HiFi__Mic1__source: Scarlett
    alsa_output.usb-Focusrite_Scarlett_Solo_USB_Y70ZEU921E21FF-00.HiFi__Line__sink: Scarlett
date:
  birth_date: "1996-02-26"
network:
  poll_interval: 1s
music: {}  # sp_dc auto-resolved from Firefox cookies; set sp_dc: "..." to override
