#!/usr/bin/env bash
set -euo pipefail

ttl=$1

expire() {
	local state=nil limit
	while :; do
		limit=()
		[[ $state == nil ]] || limit=(-t "$ttl")
		if read -r "${limit[@]}" state; then
			continue
		elif (($? > 128)); then
			/usr/bin/wl-copy "$@" --clear
			state=nil
		else
			return 1
		fi
	done < <(/usr/bin/wl-paste "$@" --watch sh -c 'cat >/dev/null; echo "$CLIPBOARD_STATE"')
}

expire &
expire --primary &
wait -n
