export const names = {
  hyprland: {
    "App Launcher": { name: "Apps" },
    "Close active window": { name: "Close" },
    "Cycle split": { name: "Split", about: "Cycles the master ratio preset: xs, default, lg." },
    "Dismiss": { name: "Dismiss", about: "Closes the top notification." },
    "Focus down": { name: "Focus ↓" },
    "Focus left": { name: "Focus ←" },
    "Focus right": { name: "Focus →" },
    "Focus up": { name: "Focus ↑" },
    "Force kill window": { name: "Kill", about: "Click a window to force-kill its process." },
    "Keymap viewer": { name: "Keymap" },
    "Layout Launcher": { name: "Layouts", about: "Opens the hyprd picker for workspace session layouts." },
    "Lock screen": { name: "Lock", about: "Full lock: hyprlock asks for the password before the session returns." },
    "Move window down": { name: "Move ↓" },
    "Move window left": { name: "Move ←" },
    "Move window right": { name: "Move →" },
    "Move window up": { name: "Move ↑" },
    "Move workspace down": { name: "Move to prev WS", about: "Moves the window to the previous workspace (2–5) and follows it." },
    "Move workspace up": { name: "Move to next WS", about: "Moves the window to the next workspace (2–5) and follows it." },
    "Privacy screen": { name: "Privacy", about: "Pseudolock: blanks the screen and pauses audio and notifications without authentication; Super+Q exits." },
    "Screen share mode": { name: "Share", about: "Share mode: changes gaps and ratios for screen sharing and hides notifications and widgets." },
    "Screenshot + annotate": { name: "Capture + edit", about: "Captures a region, opens it in satty to annotate, then copies it." },
    "Screenshot to clipboard": { name: "Capture", about: "Captures a selected region to the clipboard." },
    "Toggle floating": { name: "Float" },
    "Toggle full screen": { name: "Full screen" },
    "Toggle monocle": { name: "Monocle", about: "Floats the focused window and parks its tiled siblings until pressed again." },
    "Toggle shadow": { name: "Shadow", about: "Three-body: swaps the active slave with the window parked on the shadow workspace." },
    "Workspace 1 (music)": { name: "WS Music" },
    "Workspace 2 (chat)": { name: "WS Chat" },
    "Workspace 3 (misc)": { name: "WS Misc" },
    "Workspace 4 (primary)": { name: "WS Primary" },
    "Workspace 5 (settings)": { name: "WS Settings" },
  },
  kitty: {
    "Copy or interrupt": { name: "Copy or ^C" },
    "Copy to clipboard": { name: "Copy" },
    "Font size +1": { name: "Font +1" },
    "Font size -1": { name: "Font -1" },
    "Font size 19": { name: "Font 19pt" },
    "Host switch": { name: "Move to host", about: "Moves this window's managed tabs to another host." },
    "Hyprd tabs": { name: "Refresh tab", about: "Closes the profile tab and its processes, then recreates it; R refreshes all." },
    "Launch: clipboard": { name: "Copy output", about: "Copies the last command's output to the clipboard." },
    "Load config file": { name: "Reload config" },
    "Move tab backward": { name: "Move tab ←" },
    "Move tab forward": { name: "Move tab →" },
    "Myhints: hash": { name: "Copy hash", about: "Hints mode: labels visible hashes; typing a label copies that hash." },
    "Myhints: line": { name: "Copy line", about: "Hints mode: labels visible lines; typing a label copies that line." },
    "Myhints: path": { name: "Copy path", about: "Hints mode: labels visible paths; typing a label copies that path." },
    "Myhints: word": { name: "Copy word", about: "Hints mode: labels visible words; typing a label copies that word." },
    "New tab current": { name: "New tab" },
    "New window with cwd": { name: "New window" },
    "Paste from clipboard": { name: "Paste" },
    "Reset font size": { name: "Font reset" },
    "Scroll home": { name: "Scroll top" },
    "Scroll line down": { name: "Scroll ↓" },
    "Scroll line up": { name: "Scroll ↑" },
    "Scroll page down": { name: "Page ↓" },
    "Scroll page up": { name: "Page ↑" },
    "Send text": { name: "Newline", about: "Sends Esc+Enter, which prompt TUIs read as Alt+Enter to insert a newline." },
    "Show last command output": { name: "Last output", about: "Opens the last command's output in the pager." },
    "Show scrollback": { name: "Pager", about: "Opens the whole scrollback in the pager." },
  },
  nvim: {
    ":clast": { name: "Last qf" },
    ":cnext": { name: "Next qf" },
    ":cnfile": { name: "QF file →", about: "Jumps to the first quickfix entry in the next file." },
    ":cpfile": { name: "QF file ←", about: "Jumps to the last quickfix entry in the previous file." },
    ":cprevious": { name: "Prev qf" },
    ":crewind": { name: "First qf" },
    ":help &-default": { name: "Repeat :s", about: "Repeats the last substitution with its flags (:&&)." },
    ":help CTRL-L-default": { name: "Redraw", about: "Clears search highlight, updates diffs, and redraws." },
    ":help Y-default": { name: "Yank to EOL" },
    ":last": { name: "Last arg" },
    ":lnfile": { name: "Loc file →", about: "Jumps to the first location-list entry in the next file." },
    ":lpfile": { name: "Loc file ←", about: "Jumps to the last location-list entry in the previous file." },
    ":next": { name: "Next arg" },
    ":previous": { name: "Prev arg" },
    ":ptnext": { name: "Next ptag", about: "Shows the next matching tag in the preview window." },
    ":ptprevious": { name: "Prev ptag", about: "Shows the previous matching tag in the preview window." },
    ":rewind": { name: "First arg" },
    ":tlast": { name: "Last tag" },
    ":tnext": { name: "Next tag" },
    ":tprevious": { name: "Prev tag" },
    ":trewind": { name: "First tag" },
    "Add empty line above cursor": { name: "Blank line ↑" },
    "Add empty line below cursor": { name: "Blank line ↓" },
    "Add line above": { name: "Blank line ↑" },
    "Add line below": { name: "Blank line ↓" },
    "Backspace (no register)": { name: "X no yank" },
    "Buffer Diagnostics (Trouble)": { name: "Buffer issues" },
    "C surround": { name: "Rewrap block", about: "vim-surround: changes the surrounding pair and puts the text on its own lines." },
    "Change (no register)": { name: "c no yank" },
    "Change to EOL (no register)": { name: "C no yank" },
    "Colorschemes": { name: "Themes" },
    "Comment line": { name: "Divider" },
    "Comment quote": { name: "Quote box" },
    "Csurround": { name: "Rewrap", about: "vim-surround: changes the surrounding pair." },
    "Debug: Conditional Breakpoint": { name: "Break if" },
    "Debug: Start/Continue": { name: "Debug run" },
    "Debug: Step Into": { name: "Step into" },
    "Debug: Step Out": { name: "Step out" },
    "Debug: Step Over": { name: "Step over" },
    "Debug: Toggle Breakpoint": { name: "Toggle break" },
    "Debug: Toggle UI": { name: "Debug UI" },
    "Decrease height": { name: "Height -" },
    "Decrease width": { name: "Width -" },
    "Delete (no register)": { name: "d no yank" },
    "Delete char (no register)": { name: "x no yank" },
    "Delete to next Space": { name: "Delete to space" },
    "Diagnostics": { name: "Issues" },
    "Diagnostics (Trouble)": { name: "All issues" },
    "Disable macro playback": { name: "Macro off" },
    "Disable macro recording": { name: "Macro off" },
    "Disable macro replay": { name: "Macro off" },
    "Down (display line)": { name: "Down", about: "Moves by wrapped display lines unless a count is given." },
    "Dsurround": { name: "Unwrap", about: "vim-surround: deletes the surrounding pair." },
    "Emmet anchorize summary": { name: "URL → summary", about: "Emmet: turns the URL under the cursor into a link with a page summary." },
    "Emmet anchorize url": { name: "URL → link", about: "Emmet: turns the URL under the cursor into a link with the page title." },
    "Emmet balance tag inward": { name: "Balance in", about: "Emmet: selects the next tag pair inward." },
    "Emmet balance tag outword": { name: "Balance out", about: "Emmet: selects the enclosing tag pair." },
    "Emmet expand abbr": { name: "Expand abbr" },
    "Emmet expand word": { name: "Expand word" },
    "Emmet image encode": { name: "Image encode", about: "Emmet: converts the image under the cursor to a data URI." },
    "Emmet image size": { name: "Image size" },
    "Emmet merge lines": { name: "Merge lines" },
    "Emmet move next": { name: "Edit point →" },
    "Emmet move prev": { name: "Edit point ←" },
    "Emmet remove tag": { name: "Remove tag" },
    "Emmet split join tag": { name: "Split/join tag" },
    "Emmet toggle comment": { name: "Comment tag" },
    "Emmet update tag": { name: "Update tag" },
    "Explorer": { name: "Explore" },
    "Find directory in tree": { name: "Find dir", about: "Picks a directory and reveals it in nvim-tree." },
    "Fix spelling": { name: "Fix spell", about: "Applies the first spelling suggestion." },
    "Git status or find files": { name: "Git status", about: "Shows Git status when the tree is dirty, otherwise finds files." },
    "Half page down": { name: "Half page ↓" },
    "Half page up": { name: "Half page ↑" },
    "Highlight groups": { name: "HL groups" },
    "Increase height": { name: "Height +" },
    "Increase width": { name: "Width +" },
    "Indent paragraph": { name: "Indent para" },
    "Jump to the first diagnostic in the current buffer": { name: "First issue" },
    "Jump to the last diagnostic in the current buffer": { name: "Last issue" },
    "Jump to the next diagnostic in the current buffer": { name: "Next issue" },
    "Jump to the previous diagnostic in the current buffer": { name: "Prev issue" },
    "LSP Definitions / references / ... (Trouble)": { name: "LSP refs", about: "Trouble list of LSP definitions, references, and related locations." },
    "Lightspeed , ft": { name: "Repeat ←", about: "Lightspeed: repeats the last f/t motion backward." },
    "Lightspeed ; ft": { name: "Repeat →", about: "Lightspeed: repeats the last f/t motion forward." },
    "Lightspeed F": { name: "Find ←", about: "Lightspeed: jumps back to a character; press F again for the next match." },
    "Lightspeed S": { name: "Jump ←", about: "Lightspeed: type two characters, then a label, to jump backward." },
    "Lightspeed T": { name: "Till ←", about: "Lightspeed: jumps back to just after a character." },
    "Lightspeed f": { name: "Find →", about: "Lightspeed: jumps to a character; press f again for the next match." },
    "Lightspeed g S": { name: "Jump window", about: "Lightspeed: two-character jump into another window." },
    "Lightspeed s": { name: "Jump →", about: "Lightspeed: type two characters, then a label, to jump forward." },
    "Lightspeed t": { name: "Till →", about: "Lightspeed: jumps to just before a character." },
    "Location List (Trouble)": { name: "Loc list" },
    "Location list": { name: "Loc list" },
    "Markdown preview": { name: "MD preview" },
    "Markdown/Manage": { name: "Markdown + Lazy" },
    "Matchit normal backward": { name: "Match ←", about: "Matchit: cycles backward through the matching bracket or keyword set." },
    "Matchit normal forward": { name: "Match →", about: "Matchit: jumps to the matching bracket or keyword (if/else/end)." },
    "Matchit normal multi backward": { name: "Block start", about: "Matchit: jumps to the enclosing unmatched opening bracket or keyword." },
    "Matchit normal multi forward": { name: "Block end", about: "Matchit: jumps to the enclosing unmatched closing bracket or keyword." },
    "Next paragraph": { name: "Next para" },
    "Next search result": { name: "Next match" },
    "Open Git dirty tree": { name: "Changed files", about: "Opens nvim-tree showing only Git-changed files, fully expanded." },
    "Page down": { name: "Page ↓" },
    "Page up": { name: "Page ↑" },
    "Prev paragraph": { name: "Prev para" },
    "Prev search result": { name: "Prev match" },
    "Previous buffer": { name: "Prev buffer" },
    "Quick menu": { name: "Harpoon menu" },
    "Quickfix List (Trouble)": { name: "Quickfix list" },
    "Redo in place": { name: "Redo", about: "Redoes without moving the cursor or view." },
    "Registers": { name: "Regs" },
    "Replace word in file": { name: "Replace word", about: "Substitutes the word under the cursor across the file." },
    "Replace word in paragraph": { name: "Replace in para", about: "Substitutes the word under the cursor within the paragraph." },
    "Replace {custom pattern} in file": { name: "Replace pattern", about: "Starts :%s with an empty pattern." },
    "Resume last picker": { name: "Resume picker" },
    "Save and quit without formatting": { name: "Save quit", about: "Writes with :noautocmd, skipping formatting, then quits." },
    "Search word backward": { name: "Search word ←" },
    "Search word backward (partial)": { name: "Search part ←", about: "Like # without word boundaries, so partial matches count." },
    "Search word forward": { name: "Search word →" },
    "Search word forward (partial)": { name: "Search part →", about: "Like * without word boundaries, so partial matches count." },
    "Show diagnostics under the cursor": { name: "Show issue" },
    "Slot 1 · T": { name: "Harpoon 1" },
    "Slot 2 · E": { name: "Harpoon 2" },
    "Slot 3 · S": { name: "Harpoon 3" },
    "Slot 4 · A": { name: "Harpoon 4" },
    "Slot 5 · G": { name: "Harpoon 5" },
    "Slot 6 · F": { name: "Harpoon 6" },
    "Slot 7 · D": { name: "Harpoon 7" },
    "Spelling suggestions": { name: "Spelling" },
    "Switch": { name: "Toggle variant", about: "switch.vim: cycles the word under the cursor through its variants, such as true and false." },
    "Symbols (Trouble)": { name: "Outline" },
    "TS inspect": { name: "Inspect", about: "Shows the highlight groups and Treesitter captures under the cursor." },
    "Telescope": { name: "Pickers" },
    "Telescope builtins": { name: "All pickers" },
    "Toggle comment": { name: "Comment" },
    "Toggle comment line": { name: "Comment line" },
    "Toggle file tree": { name: "File tree" },
    "Toggle variant": { name: "Toggle variant", about: "switch.vim: cycles the word under the cursor through its variants, such as true and false." },
    "Treesitter": { name: "Syntax" },
    "Treesitter symbols": { name: "TS symbols" },
    "Undo in place": { name: "Undo", about: "Undoes without moving the cursor or view." },
    "Up (display line)": { name: "Up", about: "Moves by wrapped display lines unless a count is given." },
    "Window down": { name: "Window ↓" },
    "Window left": { name: "Window ←" },
    "Window right": { name: "Window →" },
    "Window up": { name: "Window ↑" },
    "Y ssurround": { name: "Line block", about: "vim-surround: surrounds the line and puts it on its own indented lines." },
    "Y surround": { name: "Wrap block", about: "vim-surround: surrounds the motion and puts the text on its own indented lines." },
    "Yank file as rich HTML": { name: "Yank HTML", about: "Copies the Markdown buffer to the clipboard as rich HTML." },
    "Yank file path": { name: "Yank path" },
    "Yank file path + diagnostics": { name: "Path + issues" },
    "Yank file path + last selection (or paragraph)": { name: "Path + range", about: "Yanks the file path with the last selection, or the paragraph." },
    "Yank file path + paragraph": { name: "Path + para" },
    "Yank file to clipboard": { name: "Copy file" },
    "Yank line to clipboard": { name: "Copy to EOL" },
    "Yank to clipboard": { name: "Copy" },
    "Yssurround": { name: "Wrap line" },
    "Ysurround": { name: "Wrap", about: "vim-surround: surrounds a motion with a pair." },
    "Zoxide directories": { name: "Zoxide dirs" },
    "q": { name: "Quit", about: "Maps q: to :q instead of opening the command-line window." },
    "vim.lsp.buf.code_action()": { name: "Code action" },
    "vim.lsp.buf.document_symbol()": { name: "Symbols" },
    "vim.lsp.buf.implementation()": { name: "Go to impl" },
    "vim.lsp.buf.references()": { name: "Find refs" },
    "vim.lsp.buf.rename()": { name: "Rename" },
    "vim.lsp.buf.type_definition()": { name: "Go to type" },
    "vim.lsp.codelens.run()": { name: "Run lens", about: "Runs the code lens on the current line." },
  },
  opencode: {
    "Background synchronous subagents": { name: "Detach agents", about: "Moves running synchronous subagents to the background." },
    "Backspace in input": { name: "Delete ←" },
    "Clear input field": { name: "Clear input" },
    "Close diff viewer": { name: "Close diff" },
    "Collapse diff viewer item": { name: "Collapse" },
    "Compact the session": { name: "Compact" },
    "Complete autocomplete item": { name: "Complete" },
    "Create a new session": { name: "New session" },
    "Cycle model variants": { name: "Next variant" },
    "Delete character in input": { name: "Delete →" },
    "Delete line in input": { name: "Delete line" },
    "Delete project copy": { name: "Delete copy" },
    "Delete stash entry": { name: "Delete stash" },
    "Delete to end of line in input": { name: "Delete to end" },
    "Delete to start of line in input": { name: "Delete to start" },
    "Delete word backward in input": { name: "Delete word ←" },
    "Delete word forward in input": { name: "Delete word →" },
    "Exit the application": { name: "Quit" },
    "Expand all diff viewer folders": { name: "Expand all" },
    "Expand diff viewer item": { name: "Expand" },
    "Export session to editor": { name: "Export", about: "Exports the session transcript to your editor." },
    "Go to first child session": { name: "First child", about: "Child sessions are the subagent sessions this session spawned." },
    "Go to next child session": { name: "Next child" },
    "Go to parent session": { name: "Parent" },
    "Go to previous child session": { name: "Prev child" },
    "Hide autocomplete": { name: "Dismiss" },
    "Insert newline in input": { name: "Newline" },
    "Install plugin from plugin dialog": { name: "Install" },
    "Interrupt current session": { name: "Stop" },
    "Jump to first which-key binding": { name: "Hints top" },
    "Jump to last which-key binding": { name: "Hints end" },
    "Jump to next diff file": { name: "Next file" },
    "Jump to next diff hunk": { name: "Next hunk" },
    "Jump to previous diff file": { name: "Prev file" },
    "Jump to previous diff hunk": { name: "Prev hunk" },
    "List agents": { name: "Agents" },
    "List all sessions": { name: "Sessions" },
    "List available commands": { name: "Palette" },
    "List available models": { name: "Models" },
    "List available themes": { name: "Themes" },
    "Manage queued prompts": { name: "Queued prompts" },
    "Move cursor down in input": { name: "Cursor ↓" },
    "Move cursor left in input": { name: "Cursor ←" },
    "Move cursor right in input": { name: "Cursor →" },
    "Move cursor up in input": { name: "Cursor ↑" },
    "Move down one page in dialog": { name: "Page ↓" },
    "Move to end of buffer in input": { name: "Text end" },
    "Move to end of line in input": { name: "Line end" },
    "Move to end of visual line in input": { name: "Row end", about: "Moves to the end of the wrapped visual line." },
    "Move to first dialog item": { name: "First item" },
    "Move to last dialog item": { name: "Last item" },
    "Move to next autocomplete item": { name: "Next item" },
    "Move to next dialog item": { name: "Next item" },
    "Move to previous autocomplete item": { name: "Prev item" },
    "Move to previous dialog item": { name: "Prev item" },
    "Move to start of buffer in input": { name: "Text start" },
    "Move to start of line in input": { name: "Line start" },
    "Move to start of visual line in input": { name: "Row start", about: "Moves to the start of the wrapped visual line." },
    "Move up one page in dialog": { name: "Page ↑" },
    "Move word backward in input": { name: "Word ←" },
    "Move word forward in input": { name: "Word →" },
    "Navigate to first message": { name: "First message" },
    "Navigate to last message": { name: "Last message" },
    "New project copy": { name: "New copy" },
    "Next favorite model": { name: "Next favorite" },
    "Next history item": { name: "Next prompt" },
    "Next recently used model": { name: "Recent model →" },
    "Next which-key group": { name: "Hints group →" },
    "Open external editor": { name: "Editor" },
    "Open provider list from model dialog": { name: "Connect", about: "Opens the provider list from the model dialog." },
    "Page which-key down": { name: "Hints page ↓" },
    "Page which-key up": { name: "Hints page ↑" },
    "Paste from clipboard": { name: "Paste" },
    "Pin or unpin session in the session list": { name: "Pin" },
    "Previous agent": { name: "Prev agent" },
    "Previous history item": { name: "Prev prompt" },
    "Previous recently used model": { name: "Recent model ←" },
    "Previous which-key group": { name: "Hints group ←" },
    "Redo in input": { name: "Redo" },
    "Refresh project copies": { name: "Refresh" },
    "Rename session": { name: "Rename" },
    "Scroll messages down by half page": { name: "Half page ↓" },
    "Scroll messages down by one line": { name: "Scroll ↓" },
    "Scroll messages down by one page": { name: "Page ↓" },
    "Scroll messages up by half page": { name: "Half page ↑" },
    "Scroll messages up by one line": { name: "Scroll ↑" },
    "Scroll messages up by one page": { name: "Page ↑" },
    "Scroll which-key down": { name: "Hints ↓" },
    "Scroll which-key up": { name: "Hints ↑" },
    "Select all in input": { name: "Select all" },
    "Select autocomplete item": { name: "Select" },
    "Select down in input": { name: "Sel ↓" },
    "Select left in input": { name: "Sel ←" },
    "Select right in input": { name: "Sel →" },
    "Select to end of buffer in input": { name: "Sel text end" },
    "Select to end of line in input": { name: "Sel end" },
    "Select to end of visual line in input": { name: "Sel row end", about: "Selects to the end of the wrapped visual line." },
    "Select to start of buffer in input": { name: "Sel text start" },
    "Select to start of line in input": { name: "Sel start" },
    "Select to start of visual line in input": { name: "Sel row start", about: "Selects to the start of the wrapped visual line." },
    "Select up in input": { name: "Sel ↑" },
    "Select word backward in input": { name: "Sel word ←" },
    "Select word forward in input": { name: "Sel word →" },
    "Show more diff viewer shortcuts": { name: "Diff help" },
    "Show session timeline": { name: "Timeline" },
    "Submit dialog prompt": { name: "Submit" },
    "Submit input": { name: "Submit" },
    "Submit selected dialog item": { name: "Submit" },
    "Suspend terminal": { name: "Suspend" },
    "Switch diff viewer focus": { name: "Switch focus" },
    "Switch diff viewer source": { name: "Switch source" },
    "Switch to session in quick slot 1": { name: "Session 1", about: "Switches to the session in quick slot 1." },
    "Switch to session in quick slot 2": { name: "Session 2", about: "Switches to the session in quick slot 2." },
    "Switch to session in quick slot 3": { name: "Session 3", about: "Switches to the session in quick slot 3." },
    "Switch to session in quick slot 4": { name: "Session 4", about: "Switches to the session in quick slot 4." },
    "Switch to session in quick slot 5": { name: "Session 5", about: "Switches to the session in quick slot 5." },
    "Switch to session in quick slot 6": { name: "Session 6", about: "Switches to the session in quick slot 6." },
    "Switch to session in quick slot 7": { name: "Session 7", about: "Switches to the session in quick slot 7." },
    "Switch to session in quick slot 8": { name: "Session 8", about: "Switches to the session in quick slot 8." },
    "Switch to session in quick slot 9": { name: "Session 9", about: "Switches to the session in quick slot 9." },
    "Switch which-key layout": { name: "Hints layout" },
    "Toggle MCP in MCP dialog": { name: "Toggle MCP" },
    "Toggle code block concealment in messages": { name: "Code conceal", about: "Hides or shows code blocks in messages." },
    "Toggle diff viewer file tree": { name: "File tree" },
    "Toggle diff viewer item": { name: "Toggle item" },
    "Toggle diff viewer split or unified view": { name: "Split/unified" },
    "Toggle model favorite status": { name: "Favorite" },
    "Toggle permission prompt fullscreen": { name: "Full screen" },
    "Toggle sidebar": { name: "Sidebar" },
    "Toggle single patch view": { name: "Single patch" },
    "Toggle tips on home screen": { name: "Tips" },
    "Toggle tool details visibility": { name: "Tool details" },
    "Toggle which-key panel": { name: "Hints panel", about: "Toggles the which-key panel that lists available binds." },
    "Toggle which-key pending preview": { name: "Hints preview" },
    "Undo in input": { name: "Undo" },
  },
};
