export const names = {
  hyprland: {
    "Agents tab 0": { name: "[0] Agents" },
    "Agents tab 1": { name: "[1] Agents" },
    "Agents tab 2": { name: "[2] Agents" },
    "Agents tab 3": { name: "[3] Agents" },
    "Agents tab 4": { name: "[4] Agents" },
    "App Launcher": { name: "Apps" },
    "Close active window": { name: "Close" },
    "Dismiss": { name: "Dismiss", about: "Closes the top notification." },
    "Drop-down terminal": { name: "Terminal", about: "Slides a kitty window down from the top on its own special workspace; press again to hide it." },
    "Editor tab 0": { name: "[0] Editor" },
    "Editor tab 1": { name: "[1] Editor" },
    "Editor tab 2": { name: "[2] Editor" },
    "Editor tab 3": { name: "[3] Editor" },
    "Editor tab 4": { name: "[4] Editor" },
    "Focus down": { name: "Focus ↓" },
    "Focus left": { name: "Focus ←" },
    "Focus right": { name: "Focus →" },
    "Focus up": { name: "Focus ↑" },
    "Force kill window": { name: "Kill", about: "Click a window to force-kill its process." },
    "Keymap viewer": { name: "Keymap" },
    "Layout Launcher": { name: "Layouts", about: "Opens the hyprd picker for workspace session layouts." },
    "Lock screen": { name: "Lock", about: "Full lock: asks for the password before the session returns." },
    "Move window down": { name: "Move ↓" },
    "Move window left": { name: "Move ←" },
    "Move window right": { name: "Move →" },
    "Move window up": { name: "Move ↑" },
    "Move workspace down": { name: "Carry ↓", about: "Carries the window to the previous workspace, skipping music, and follows it." },
    "Move workspace up": { name: "Carry ↑", about: "Carries the window to the next workspace, skipping music, and follows it." },
    "Screen share mode": { name: "Share", about: "Share mode: changes gaps and ratios for screen sharing and hides notifications and widgets." },
    "Screenshot + annotate": { name: "Markup", about: "Captures a region, opens it in satty to annotate, then copies it." },
    "Screenshot to clipboard": { name: "Capture", about: "Captures a selected region to the clipboard." },
    "Split narrow": { name: "Narrow", about: "Narrows the master from default; from any other ratio, returns to default." },
    "Split wide": { name: "Wide", about: "Widens the master from default; from any other ratio, returns to default." },
    "Swap master": { name: "Swap", about: "Three-body: promotes the shadow to master; the old master becomes the shadow." },
    "Toggle floating": { name: "Float" },
    "Toggle full screen": { name: "Full screen" },
    "Toggle monocle": { name: "Monocle", about: "Floats the focused window and parks its tiled siblings until pressed again." },
    "Toggle shadow": { name: "Shadow", about: "Three-body: swaps the active slave with the window parked on the shadow workspace." },
    "Wake displays": { name: "Wake" },
    "Workspace 1 (misc)": { name: "[1] Misc" },
    "Workspace 2 (chat)": { name: "[2] Chat" },
    "Workspace 3 (work)": { name: "[3] Work" },
    "Workspace 4 (personal)": { name: "[4] Personal" },
    "Workspace 5 (dotfiles)": { name: "[5] Dotfiles" },
    "Workspace 6 (music)": { name: "[6] Music" },
  },
  kitty: {
    "Close tab": { name: "Tab −" },
    "Close window": { name: "Pane −" },
    "Copy or interrupt": { name: "Copy", about: "Copies the selection, or sends Ctrl+C when nothing is selected." },
    "Copy to clipboard": { name: "Copy" },
    "Font size +1": { name: "Font +" },
    "Font size -1": { name: "Font −" },
    "Font size 19": { name: "Font 19" },
    "Host switch": { name: "Migrate", about: "Moves this window's managed tabs to another host." },
    "Hyprd tabs": { name: "Refresh", about: "Closes the profile tab and its processes, then recreates it; R refreshes all." },
    "Launch: clipboard": { name: "Copy output", about: "Copies the last command's output to the clipboard." },
    "Load config file": { name: "Reload" },
    "Move tab backward": { name: "Move ←", about: "Moves the tab one place left." },
    "Move tab forward": { name: "Move →", about: "Moves the tab one place right." },
    "Myhints: hash": { name: "Hash", about: "Hints mode: labels visible hashs; typing a label copies that hash." },
    "Myhints: line": { name: "Line", about: "Hints mode: labels visible lines; typing a label copies that line." },
    "Myhints: path": { name: "Path", about: "Hints mode: labels visible paths; typing a label copies that path." },
    "Myhints: word": { name: "Word", about: "Hints mode: labels visible words; typing a label copies that word." },
    "New tab current": { name: "Tab +" },
    "New window with cwd": { name: "Pane +", about: "Splits a new pane in the current directory." },
    "Next layout": { name: "Layout" },
    "Next prompt": { name: "Prompt →" },
    "Next tab": { name: "Tab →" },
    "Next window": { name: "Pane →" },
    "Paste from clipboard": { name: "Paste" },
    "Previous prompt": { name: "Prompt ←" },
    "Previous tab": { name: "Tab ←" },
    "Previous window": { name: "Pane ←" },
    "Reset font size": { name: "Reset", about: "Restores the default font size." },
    "Scroll end": { name: "Bottom" },
    "Scroll home": { name: "Top" },
    "Scroll line down": { name: "Line ↓" },
    "Scroll line up": { name: "Line ↑" },
    "Scroll page down": { name: "Page ↓" },
    "Scroll page up": { name: "Page ↑" },
    "Send text": { name: "Newline", about: "Sends Esc+Enter, which prompt TUIs read as Alt+Enter to insert a newline." },
    "Show last command output": { name: "Output", about: "Opens the last command's output in the pager." },
    "Show scrollback": { name: "Pager", about: "Opens the whole scrollback in the pager." },
    "Tab 1": { name: "[1] Tab" },
    "Tab 2": { name: "[2] Tab" },
    "Tab 3": { name: "[3] Tab" },
    "Tab 4": { name: "[4] Tab" },
    "Tab 5": { name: "[5] Tab" },
    "Unicode input": { name: "Unicode" },
  },
  nvim: {
    ":clast": { name: "QF ⇥", about: "Jumps to the last quickfix entry." },
    ":cnext": { name: "QF →", about: "Jumps to the next quickfix entry." },
    ":cnfile": { name: "File →", about: "Jumps to the first quickfix entry in the next file." },
    ":cpfile": { name: "File ←", about: "Jumps to the last quickfix entry in the previous file." },
    ":cprevious": { name: "QF ←", about: "Jumps to the previous quickfix entry." },
    ":crewind": { name: "QF ⇤", about: "Jumps to the first quickfix entry." },
    ":help &-default": { name: "Resub", about: "Repeats the last :s substitution with its flags." },
    ":help CTRL-L-default": { name: "Redraw", about: "Clears search highlight, updates diffs, and redraws." },
    ":help Y-default": { name: "Yank $" },
    ":last": { name: "Arg ⇥", about: "Edits the last file in the argument list." },
    ":lnfile": { name: "File →", about: "Jumps to the first location-list entry in the next file." },
    ":lpfile": { name: "File ←", about: "Jumps to the last location-list entry in the previous file." },
    ":next": { name: "Arg →", about: "Edits the next file in the argument list." },
    ":previous": { name: "Arg ←", about: "Edits the previous file in the argument list." },
    ":ptnext": { name: "Peek →", about: "Shows the next matching tag in the preview window." },
    ":ptprevious": { name: "Peek ←", about: "Shows the previous matching tag in the preview window." },
    ":rewind": { name: "Arg ⇤", about: "Edits the first file in the argument list." },
    ":tlast": { name: "Tag ⇥" },
    ":tnext": { name: "Tag →" },
    ":tprevious": { name: "Tag ←" },
    ":trewind": { name: "Tag ⇤" },
    "Add empty line above cursor": { name: "Blank ↑" },
    "Add empty line below cursor": { name: "Blank ↓" },
    "Add line above": { name: "Blank ↑" },
    "Add line below": { name: "Blank ↓" },
    "Backspace (no register)": { name: "Delete ←", about: "Uses the black-hole register, so registers keep their contents." },
    "Buffer Diagnostics (Trouble)": { name: "File", about: "Trouble list of diagnostics in this buffer." },
    "Buffer/Debug": { name: "Buffer" },
    "C surround": { name: "Rewrap ↵", about: "vim-surround: changes the surrounding pair and puts the text on its own lines." },
    "Change (no register)": { name: "Change", about: "Uses the black-hole register, so registers keep their contents." },
    "Change to EOL (no register)": { name: "Change $", about: "Uses the black-hole register, so registers keep their contents." },
    "Clear search": { name: "Clear", about: "Clears the last search pattern." },
    "Code/Change": { name: "Code" },
    "Colorschemes": { name: "Themes" },
    "Comment box": { name: "Box" },
    "Comment line": { name: "Divider" },
    "Comment quote": { name: "Quote" },
    "Csurround": { name: "Rewrap", about: "vim-surround: changes the surrounding pair." },
    "Debug: Conditional Breakpoint": { name: "Break if" },
    "Debug: Start/Continue": { name: "Debug", about: "Starts debugging, or continues to the next breakpoint." },
    "Debug: Step Into": { name: "Step ↓", about: "Steps into the call." },
    "Debug: Step Out": { name: "Step ↑", about: "Steps out of the current function." },
    "Debug: Step Over": { name: "Step →", about: "Steps over the call." },
    "Debug: Toggle Breakpoint": { name: "Break" },
    "Debug: Toggle UI": { name: "Panels", about: "Toggles the debugger UI panels." },
    "Decrease height": { name: "Height −" },
    "Decrease width": { name: "Width −" },
    "Delete (no register)": { name: "Delete", about: "Uses the black-hole register, so registers keep their contents." },
    "Delete buffer": { name: "Close", about: "Deletes the buffer with :bd!, discarding unsaved changes." },
    "Delete char (no register)": { name: "Delete →", about: "Uses the black-hole register, so registers keep their contents." },
    "Delete to next Space": { name: "Delete ␣", about: "Deletes up to the next space (dt␣)." },
    "Delete/Database": { name: "Delete" },
    "Diagnostics": { name: "Issues" },
    "Diagnostics (Trouble)": { name: "Project", about: "Trouble list of diagnostics across the project." },
    "Disable macro playback": { name: "Off", about: "Disabled so macros cannot be recorded or played by accident." },
    "Disable macro recording": { name: "Off", about: "Disabled so macros cannot be recorded or played by accident." },
    "Disable macro replay": { name: "Off", about: "Disabled so macros cannot be recorded or played by accident." },
    "Down (display line)": { name: "Down", about: "Moves by wrapped display lines unless a count is given." },
    "Dsurround": { name: "Unwrap", about: "vim-surround: deletes the surrounding pair." },
    "Easy Align": { name: "Align" },
    "Emmet anchorize summary": { name: "Summary", about: "Emmet: turns the URL under the cursor into a link with a page summary." },
    "Emmet anchorize url": { name: "Link", about: "Emmet: turns the URL under the cursor into a link with the page title." },
    "Emmet balance tag inward": { name: "Inward", about: "Emmet: selects the next tag pair inward." },
    "Emmet balance tag outword": { name: "Outward", about: "Emmet: selects the enclosing tag pair." },
    "Emmet expand abbr": { name: "Expand", about: "Emmet: expands the abbreviation." },
    "Emmet expand word": { name: "Word", about: "Emmet: expands the word before the cursor as an abbreviation." },
    "Emmet image encode": { name: "Encode", about: "Emmet: converts the image under the cursor to a data URI." },
    "Emmet image size": { name: "Size", about: "Emmet: sets width and height from the image file." },
    "Emmet merge lines": { name: "Merge" },
    "Emmet move next": { name: "Point →", about: "Emmet: moves to the next edit point." },
    "Emmet move prev": { name: "Point ←", about: "Emmet: moves to the previous edit point." },
    "Emmet remove tag": { name: "Remove", about: "Emmet: removes the tag under the cursor." },
    "Emmet split join tag": { name: "Split/join", about: "Emmet: toggles a tag between an open/close pair and a self-closing tag." },
    "Emmet toggle comment": { name: "Comment" },
    "Emmet update tag": { name: "Update", about: "Emmet: replaces the tag with a new abbreviation." },
    "Explorer": { name: "Explore" },
    "Find directory in tree": { name: "Folder", about: "Picks a directory and reveals it in nvim-tree." },
    "Find files": { name: "Files" },
    "Fix spelling": { name: "Correct", about: "Applies the first spelling suggestion." },
    "Force quit": { name: "Quit!" },
    "Git Hunk": { name: "Hunk" },
    "Git files": { name: "Tracked", about: "Finds Git-tracked files." },
    "Git status or find files": { name: "Status", about: "Shows Git status when the tree is dirty, otherwise finds files." },
    "Go to EOF": { name: "Bottom" },
    "Half page down": { name: "Half ↓" },
    "Half page up": { name: "Half ↑" },
    "Help tags": { name: "Help" },
    "Highlight groups": { name: "Groups", about: "Picks a highlight group." },
    "Increase height": { name: "Height +" },
    "Increase width": { name: "Width +" },
    "Indent file": { name: "Indent", about: "Reindents the whole file." },
    "Indent paragraph": { name: "Indent", about: "Reindents the paragraph." },
    "Join lines": { name: "Join" },
    "Jump back": { name: "Back", about: "Jumps to the previous jumplist position." },
    "Jump forward": { name: "Forward", about: "Jumps to the next jumplist position." },
    "Jump to the first diagnostic in the current buffer": { name: "Issue ⇤" },
    "Jump to the last diagnostic in the current buffer": { name: "Issue ⇥" },
    "Jump to the next diagnostic in the current buffer": { name: "Issue →" },
    "Jump to the previous diagnostic in the current buffer": { name: "Issue ←" },
    "LSP Definitions / references / ... (Trouble)": { name: "LSP", about: "Trouble list of LSP definitions, references, and related locations." },
    "Lightspeed , ft": { name: "Repeat ←", about: "Lightspeed: repeats the last f/t motion backward." },
    "Lightspeed ; ft": { name: "Repeat →", about: "Lightspeed: repeats the last f/t motion forward." },
    "Lightspeed F": { name: "Find ←", about: "Lightspeed: jumps back to a character; press F again for the next match." },
    "Lightspeed S": { name: "Jump ←", about: "Lightspeed: type two characters, then a label, to jump backward." },
    "Lightspeed T": { name: "Till ←", about: "Lightspeed: jumps back to just after a character." },
    "Lightspeed f": { name: "Find →", about: "Lightspeed: jumps to a character; press f again for the next match." },
    "Lightspeed g S": { name: "Jump", about: "Lightspeed: two-character jump into another window." },
    "Lightspeed s": { name: "Jump →", about: "Lightspeed: type two characters, then a label, to jump forward." },
    "Lightspeed t": { name: "Till →", about: "Lightspeed: jumps to just before a character." },
    "Live grep": { name: "Grep" },
    "Location List (Trouble)": { name: "Loclist" },
    "Location list": { name: "Loclist" },
    "Man pages": { name: "Man" },
    "Markdown preview": { name: "Preview" },
    "Markdown/Manage": { name: "Markdown", about: "Markdown preview and export, plus plugin updates." },
    "Matchit normal backward": { name: "Pair ←", about: "Matchit: cycles backward through the matching bracket or keyword set." },
    "Matchit normal forward": { name: "Pair →", about: "Matchit: jumps to the matching bracket or keyword (if/else/end)." },
    "Matchit normal multi backward": { name: "Block ←", about: "Matchit: jumps to the enclosing unmatched opening bracket or keyword." },
    "Matchit normal multi forward": { name: "Block →", about: "Matchit: jumps to the enclosing unmatched closing bracket or keyword." },
    "Move to new tab": { name: "Detach", about: "Moves the window into a new tab." },
    "Next buffer": { name: "Buffer →" },
    "Next paragraph": { name: "Para →" },
    "Next search result": { name: "Match →" },
    "Next tab": { name: "Tab →" },
    "Open Git dirty tree": { name: "Changes", about: "Opens nvim-tree showing only Git-changed files, fully expanded." },
    "Open URL": { name: "URL", about: "Opens the URL or file under the cursor with xdg-open." },
    "Page down": { name: "Page ↓" },
    "Page up": { name: "Page ↑" },
    "Pin file": { name: "Pin" },
    "Prev paragraph": { name: "Para ←" },
    "Prev search result": { name: "Match ←" },
    "Prev tab": { name: "Tab ←" },
    "Previous buffer": { name: "Buffer ←" },
    "Quick menu": { name: "Menu" },
    "Quickfix List (Trouble)": { name: "Quickfix" },
    "Quickfix list": { name: "Quickfix" },
    "Recent files": { name: "Recent" },
    "Redo in place": { name: "Redo", about: "Redoes without moving the cursor or view." },
    "Registers": { name: "Regs" },
    "Replace word in file": { name: "Word", about: "Substitutes the word under the cursor across the file." },
    "Replace word in paragraph": { name: "Para", about: "Substitutes the word under the cursor within the paragraph." },
    "Replace {custom pattern} in file": { name: "Pattern", about: "Starts :%s with an empty pattern." },
    "Replace/Rename": { name: "Replace" },
    "Restart LSP": { name: "Restart", about: "Restarts the LSP clients." },
    "Resume last picker": { name: "Resume" },
    "Save and quit without formatting": { name: "Exit", about: "Writes with :noautocmd, skipping formatting, then quits." },
    "Search history": { name: "History" },
    "Search word backward": { name: "Word ←" },
    "Search word backward (partial)": { name: "Partial ←", about: "Like # without word boundaries, so partial matches count." },
    "Search word forward": { name: "Word →" },
    "Search word forward (partial)": { name: "Partial →", about: "Like * without word boundaries, so partial matches count." },
    "Search/Spell": { name: "Search" },
    "Show diagnostics under the cursor": { name: "Issue", about: "Shows the diagnostics under the cursor in a float." },
    "Slot 1 · T": { name: "[1] File" },
    "Slot 2 · E": { name: "[2] File" },
    "Slot 3 · S": { name: "[3] File" },
    "Slot 4 · A": { name: "[4] File" },
    "Slot 5 · G": { name: "[5] File" },
    "Slot 6 · F": { name: "[6] File" },
    "Slot 7 · D": { name: "[7] File" },
    "Spelling suggestions": { name: "Spelling" },
    "Switch": { name: "Variant", about: "switch.vim: cycles the word under the cursor through its variants, such as true and false." },
    "Symbols (Trouble)": { name: "Outline" },
    "TS inspect": { name: "Inspect", about: "Shows the highlight groups and Treesitter captures under the cursor." },
    "Telescope": { name: "Pickers" },
    "Telescope builtins": { name: "Builtins", about: "Lists every Telescope picker." },
    "Toggle colors": { name: "Colors", about: "Toggles colorizer highlighting of color codes." },
    "Toggle comment": { name: "Comment" },
    "Toggle comment line": { name: "Line" },
    "Toggle file tree": { name: "Tree" },
    "Toggle spell": { name: "Spell" },
    "Toggle variant": { name: "Variant", about: "switch.vim: cycles the word under the cursor through its variants, such as true and false." },
    "Toggle wrap": { name: "Wrap", about: "Toggles line wrapping." },
    "Treesitter": { name: "Syntax" },
    "Treesitter symbols": { name: "Symbols" },
    "Undo in place": { name: "Undo", about: "Undoes without moving the cursor or view." },
    "Undo tree": { name: "Tree" },
    "Up (display line)": { name: "Up", about: "Moves by wrapped display lines unless a count is given." },
    "Update plugins": { name: "Update" },
    "Window down": { name: "Focus ↓" },
    "Window left": { name: "Focus ←" },
    "Window right": { name: "Focus →" },
    "Window up": { name: "Focus ↑" },
    "Y ssurround": { name: "Line ↵", about: "vim-surround: surrounds the line and puts it on its own indented lines." },
    "Y surround": { name: "Wrap ↵", about: "vim-surround: surrounds the motion and puts the text on its own indented lines." },
    "Yank file as rich HTML": { name: "HTML", about: "Copies the Markdown buffer to the clipboard as rich HTML." },
    "Yank file path": { name: "Path" },
    "Yank file path + diagnostics": { name: "Path + issues" },
    "Yank file path + last selection (or paragraph)": { name: "Path + range", about: "Yanks the file path with the last selection, or the paragraph." },
    "Yank file path + paragraph": { name: "Path + para" },
    "Yank file to clipboard": { name: "Copy %", about: "Copies the whole file to the clipboard." },
    "Yank line to clipboard": { name: "Copy $" },
    "Yank to clipboard": { name: "Copy" },
    "Yssurround": { name: "Line", about: "vim-surround: surrounds the whole line." },
    "Ysurround": { name: "Wrap", about: "vim-surround: surrounds a motion with a pair." },
    "Zoxide directories": { name: "Zoxide" },
    "q": { name: "Quit", about: "Maps q: to :q instead of opening the command-line window." },
    "vim.lsp.buf.code_action()": { name: "Actions" },
    "vim.lsp.buf.document_symbol()": { name: "Symbols" },
    "vim.lsp.buf.implementation()": { name: "Impl" },
    "vim.lsp.buf.references()": { name: "Usages" },
    "vim.lsp.buf.rename()": { name: "Rename" },
    "vim.lsp.buf.type_definition()": { name: "Type" },
    "vim.lsp.codelens.run()": { name: "Lens", about: "Runs the code lens on the current line." },
  },
  opencode: {
    "Background synchronous subagents": { name: "Detach", about: "Moves running synchronous subagents to the background." },
    "Backspace in input": { name: "Delete ←" },
    "Clear input field": { name: "Clear" },
    "Close diff viewer": { name: "Close" },
    "Collapse diff viewer item": { name: "Collapse" },
    "Compact the session": { name: "Compact" },
    "Complete autocomplete item": { name: "Complete" },
    "Copy message": { name: "Copy" },
    "Create a new session": { name: "New" },
    "Cycle model variants": { name: "Variant" },
    "Delete character in input": { name: "Delete →" },
    "Delete line in input": { name: "Delete line" },
    "Delete project copy": { name: "Delete" },
    "Delete session": { name: "Delete" },
    "Delete stash entry": { name: "Delete" },
    "Delete to end of line in input": { name: "Line ⌦", about: "Deletes to the end of the line." },
    "Delete to start of line in input": { name: "Line ⌫", about: "Deletes to the start of the line." },
    "Delete word backward in input": { name: "Word ⌫" },
    "Delete word forward in input": { name: "Word ⌦" },
    "Exit the application": { name: "Quit" },
    "Expand all diff viewer folders": { name: "Unfold", about: "Expands every folder in the diff file tree." },
    "Expand diff viewer item": { name: "Expand" },
    "Export session to editor": { name: "Export", about: "Exports the session transcript to your editor." },
    "Go to first child session": { name: "Child", about: "Enters the first child session; child sessions are subagent sessions." },
    "Go to next child session": { name: "Child →" },
    "Go to parent session": { name: "Parent" },
    "Go to previous child session": { name: "Child ←" },
    "Hide autocomplete": { name: "Dismiss" },
    "Insert newline in input": { name: "Newline" },
    "Install plugin from plugin dialog": { name: "Install" },
    "Interrupt current session": { name: "Stop" },
    "Jump to first which-key binding": { name: "Hints ⤒" },
    "Jump to last which-key binding": { name: "Hints ⤓" },
    "Jump to next diff file": { name: "File →" },
    "Jump to next diff hunk": { name: "Hunk →" },
    "Jump to previous diff file": { name: "File ←" },
    "Jump to previous diff hunk": { name: "Hunk ←" },
    "List agents": { name: "Agents" },
    "List all sessions": { name: "Sessions" },
    "List available commands": { name: "Palette" },
    "List available models": { name: "Models" },
    "List available themes": { name: "Themes" },
    "Manage queued prompts": { name: "Queue" },
    "Move cursor down in input": { name: "Cursor ↓" },
    "Move cursor left in input": { name: "Cursor ←" },
    "Move cursor right in input": { name: "Cursor →" },
    "Move cursor up in input": { name: "Cursor ↑" },
    "Move down one page in dialog": { name: "Page ↓" },
    "Move to end of buffer in input": { name: "Bottom" },
    "Move to end of line in input": { name: "End" },
    "Move to end of visual line in input": { name: "Row ⇥", about: "Moves to the end of the wrapped visual line." },
    "Move to first dialog item": { name: "First" },
    "Move to last dialog item": { name: "Last" },
    "Move to next autocomplete item": { name: "Next" },
    "Move to next dialog item": { name: "Next" },
    "Move to previous autocomplete item": { name: "Prev" },
    "Move to previous dialog item": { name: "Prev" },
    "Move to start of buffer in input": { name: "Top" },
    "Move to start of line in input": { name: "Home" },
    "Move to start of visual line in input": { name: "Row ⇤", about: "Moves to the start of the wrapped visual line." },
    "Move up one page in dialog": { name: "Page ↑" },
    "Move word backward in input": { name: "Word ←" },
    "Move word forward in input": { name: "Word →" },
    "Navigate to first message": { name: "First", about: "Scrolls to the first message." },
    "Navigate to last message": { name: "Last", about: "Scrolls to the last message." },
    "New project copy": { name: "New" },
    "Next agent": { name: "Agent →" },
    "Next favorite model": { name: "Favorite →" },
    "Next history item": { name: "History ↓" },
    "Next recently used model": { name: "Recent →", about: "Switches to the next recently used model." },
    "Next which-key group": { name: "Group →", about: "Which-key: shows the next group." },
    "Open external editor": { name: "Editor" },
    "Open provider list from model dialog": { name: "Connect", about: "Opens the provider list from the model dialog." },
    "Page which-key down": { name: "Hints ⇟" },
    "Page which-key up": { name: "Hints ⇞" },
    "Paste from clipboard": { name: "Paste" },
    "Pin or unpin session in the session list": { name: "Pin" },
    "Previous agent": { name: "Agent ←" },
    "Previous history item": { name: "History ↑" },
    "Previous recently used model": { name: "Recent ←", about: "Switches to the previous recently used model." },
    "Previous which-key group": { name: "Group ←", about: "Which-key: shows the previous group." },
    "Redo in input": { name: "Redo" },
    "Redo message": { name: "Redo", about: "Restores the last undone message." },
    "Refresh project copies": { name: "Refresh" },
    "Rename session": { name: "Rename" },
    "Scroll messages down by half page": { name: "Half ↓" },
    "Scroll messages down by one line": { name: "Line ↓" },
    "Scroll messages down by one page": { name: "Page ↓" },
    "Scroll messages up by half page": { name: "Half ↑" },
    "Scroll messages up by one line": { name: "Line ↑" },
    "Scroll messages up by one page": { name: "Page ↑" },
    "Scroll which-key down": { name: "Hints ↓" },
    "Scroll which-key up": { name: "Hints ↑" },
    "Select all in input": { name: "All" },
    "Select autocomplete item": { name: "Select" },
    "Select down in input": { name: "Select ↓" },
    "Select left in input": { name: "Select ←" },
    "Select right in input": { name: "Select →" },
    "Select to end of buffer in input": { name: "Bottom", about: "Selects to the end of the input." },
    "Select to end of line in input": { name: "End", about: "Selects to the end of the line." },
    "Select to end of visual line in input": { name: "Row ⇥", about: "Selects to the end of the wrapped visual line." },
    "Select to start of buffer in input": { name: "Top", about: "Selects to the start of the input." },
    "Select to start of line in input": { name: "Home", about: "Selects to the start of the line." },
    "Select to start of visual line in input": { name: "Row ⇤", about: "Selects to the start of the wrapped visual line." },
    "Select up in input": { name: "Select ↑" },
    "Select word backward in input": { name: "Word ←", about: "Selects to the previous word start." },
    "Select word forward in input": { name: "Word →", about: "Selects to the next word end." },
    "Show more diff viewer shortcuts": { name: "Help" },
    "Show session timeline": { name: "Timeline" },
    "Submit dialog prompt": { name: "Submit" },
    "Submit input": { name: "Submit" },
    "Submit selected dialog item": { name: "Submit" },
    "Suspend terminal": { name: "Suspend" },
    "Switch diff viewer focus": { name: "Focus" },
    "Switch diff viewer source": { name: "Source" },
    "Switch to session in quick slot 1": { name: "[1] Slot", about: "Switches to the session in quick slot 1." },
    "Switch to session in quick slot 2": { name: "[2] Slot", about: "Switches to the session in quick slot 2." },
    "Switch to session in quick slot 3": { name: "[3] Slot", about: "Switches to the session in quick slot 3." },
    "Switch to session in quick slot 4": { name: "[4] Slot", about: "Switches to the session in quick slot 4." },
    "Switch to session in quick slot 5": { name: "[5] Slot", about: "Switches to the session in quick slot 5." },
    "Switch to session in quick slot 6": { name: "[6] Slot", about: "Switches to the session in quick slot 6." },
    "Switch to session in quick slot 7": { name: "[7] Slot", about: "Switches to the session in quick slot 7." },
    "Switch to session in quick slot 8": { name: "[8] Slot", about: "Switches to the session in quick slot 8." },
    "Switch to session in quick slot 9": { name: "[9] Slot", about: "Switches to the session in quick slot 9." },
    "Switch which-key layout": { name: "Layout", about: "Switches the which-key panel layout." },
    "Toggle MCP in MCP dialog": { name: "Enable", about: "Enables or disables the selected MCP server." },
    "Toggle code block concealment in messages": { name: "Conceal", about: "Hides or shows code blocks in messages." },
    "Toggle diff viewer file tree": { name: "Tree" },
    "Toggle diff viewer item": { name: "Fold" },
    "Toggle diff viewer split or unified view": { name: "Split", about: "Switches between split and unified diff views." },
    "Toggle model favorite status": { name: "Favorite" },
    "Toggle permission prompt fullscreen": { name: "Maximize" },
    "Toggle plugin": { name: "Enable", about: "Enables or disables the selected plugin." },
    "Toggle sidebar": { name: "Sidebar" },
    "Toggle single patch view": { name: "Single", about: "Toggles showing one patch at a time." },
    "Toggle tips on home screen": { name: "Tips" },
    "Toggle tool details visibility": { name: "Details", about: "Shows or hides tool call details." },
    "Toggle which-key panel": { name: "Hints", about: "Toggles the which-key panel that lists available binds." },
    "Toggle which-key pending preview": { name: "Preview", about: "Toggles the which-key preview of pending chord keys." },
    "Undo in input": { name: "Undo" },
    "Undo message": { name: "Undo", about: "Reverts the last message and its file changes." },
    "View status": { name: "Status" },
  },
};
