// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/ewwd/providers/canvas.proto

package providers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CanvasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*CanvasRequest_Track `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanvasRequest) Reset() {
	*x = CanvasRequest{}
	mi := &file_internal_ewwd_providers_canvas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanvasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanvasRequest) ProtoMessage() {}

func (x *CanvasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ewwd_providers_canvas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanvasRequest.ProtoReflect.Descriptor instead.
func (*CanvasRequest) Descriptor() ([]byte, []int) {
	return file_internal_ewwd_providers_canvas_proto_rawDescGZIP(), []int{0}
}

func (x *CanvasRequest) GetTracks() []*CanvasRequest_Track {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type CanvasResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Canvases      []*CanvasResponse_Canvas `protobuf:"bytes,1,rep,name=canvases,proto3" json:"canvases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanvasResponse) Reset() {
	*x = CanvasResponse{}
	mi := &file_internal_ewwd_providers_canvas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanvasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanvasResponse) ProtoMessage() {}

func (x *CanvasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ewwd_providers_canvas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanvasResponse.ProtoReflect.Descriptor instead.
func (*CanvasResponse) Descriptor() ([]byte, []int) {
	return file_internal_ewwd_providers_canvas_proto_rawDescGZIP(), []int{1}
}

func (x *CanvasResponse) GetCanvases() []*CanvasResponse_Canvas {
	if x != nil {
		return x.Canvases
	}
	return nil
}

type CanvasRequest_Track struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackUri      string                 `protobuf:"bytes,1,opt,name=track_uri,json=trackUri,proto3" json:"track_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanvasRequest_Track) Reset() {
	*x = CanvasRequest_Track{}
	mi := &file_internal_ewwd_providers_canvas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanvasRequest_Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanvasRequest_Track) ProtoMessage() {}

func (x *CanvasRequest_Track) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ewwd_providers_canvas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanvasRequest_Track.ProtoReflect.Descriptor instead.
func (*CanvasRequest_Track) Descriptor() ([]byte, []int) {
	return file_internal_ewwd_providers_canvas_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CanvasRequest_Track) GetTrackUri() string {
	if x != nil {
		return x.TrackUri
	}
	return ""
}

type CanvasResponse_Canvas struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Id            string                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CanvasUrl     string                        `protobuf:"bytes,2,opt,name=canvas_url,json=canvasUrl,proto3" json:"canvas_url,omitempty"`
	TrackUri      string                        `protobuf:"bytes,5,opt,name=track_uri,json=trackUri,proto3" json:"track_uri,omitempty"`
	Artist        *CanvasResponse_Canvas_Artist `protobuf:"bytes,6,opt,name=artist,proto3" json:"artist,omitempty"`
	OtherId       string                        `protobuf:"bytes,9,opt,name=other_id,json=otherId,proto3" json:"other_id,omitempty"`
	CanvasUri     string                        `protobuf:"bytes,11,opt,name=canvas_uri,json=canvasUri,proto3" json:"canvas_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanvasResponse_Canvas) Reset() {
	*x = CanvasResponse_Canvas{}
	mi := &file_internal_ewwd_providers_canvas_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanvasResponse_Canvas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanvasResponse_Canvas) ProtoMessage() {}

func (x *CanvasResponse_Canvas) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ewwd_providers_canvas_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanvasResponse_Canvas.ProtoReflect.Descriptor instead.
func (*CanvasResponse_Canvas) Descriptor() ([]byte, []int) {
	return file_internal_ewwd_providers_canvas_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CanvasResponse_Canvas) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CanvasResponse_Canvas) GetCanvasUrl() string {
	if x != nil {
		return x.CanvasUrl
	}
	return ""
}

func (x *CanvasResponse_Canvas) GetTrackUri() string {
	if x != nil {
		return x.TrackUri
	}
	return ""
}

func (x *CanvasResponse_Canvas) GetArtist() *CanvasResponse_Canvas_Artist {
	if x != nil {
		return x.Artist
	}
	return nil
}

func (x *CanvasResponse_Canvas) GetOtherId() string {
	if x != nil {
		return x.OtherId
	}
	return ""
}

func (x *CanvasResponse_Canvas) GetCanvasUri() string {
	if x != nil {
		return x.CanvasUri
	}
	return ""
}

type CanvasResponse_Canvas_Artist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtistUri     string                 `protobuf:"bytes,1,opt,name=artist_uri,json=artistUri,proto3" json:"artist_uri,omitempty"`
	ArtistName    string                 `protobuf:"bytes,2,opt,name=artist_name,json=artistName,proto3" json:"artist_name,omitempty"`
	ArtistImgUrl  string                 `protobuf:"bytes,3,opt,name=artist_img_url,json=artistImgUrl,proto3" json:"artist_img_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanvasResponse_Canvas_Artist) Reset() {
	*x = CanvasResponse_Canvas_Artist{}
	mi := &file_internal_ewwd_providers_canvas_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanvasResponse_Canvas_Artist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanvasResponse_Canvas_Artist) ProtoMessage() {}

func (x *CanvasResponse_Canvas_Artist) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ewwd_providers_canvas_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanvasResponse_Canvas_Artist.ProtoReflect.Descriptor instead.
func (*CanvasResponse_Canvas_Artist) Descriptor() ([]byte, []int) {
	return file_internal_ewwd_providers_canvas_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *CanvasResponse_Canvas_Artist) GetArtistUri() string {
	if x != nil {
		return x.ArtistUri
	}
	return ""
}

func (x *CanvasResponse_Canvas_Artist) GetArtistName() string {
	if x != nil {
		return x.ArtistName
	}
	return ""
}

func (x *CanvasResponse_Canvas_Artist) GetArtistImgUrl() string {
	if x != nil {
		return x.ArtistImgUrl
	}
	return ""
}

var File_internal_ewwd_providers_canvas_proto protoreflect.FileDescriptor

const file_internal_ewwd_providers_canvas_proto_rawDesc = "" +
	"\n" +
	"$internal/ewwd/providers/canvas.proto\x12\tproviders\"m\n" +
	"\rCanvasRequest\x126\n" +
	"\x06tracks\x18\x01 \x03(\v2\x1e.providers.CanvasRequest.TrackR\x06tracks\x1a$\n" +
	"\x05Track\x12\x1b\n" +
	"\ttrack_uri\x18\x01 \x01(\tR\btrackUri\"\x90\x03\n" +
	"\x0eCanvasResponse\x12<\n" +
	"\bcanvases\x18\x01 \x03(\v2 .providers.CanvasResponse.CanvasR\bcanvases\x1a\xbf\x02\n" +
	"\x06Canvas\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"canvas_url\x18\x02 \x01(\tR\tcanvasUrl\x12\x1b\n" +
	"\ttrack_uri\x18\x05 \x01(\tR\btrackUri\x12?\n" +
	"\x06artist\x18\x06 \x01(\v2'.providers.CanvasResponse.Canvas.ArtistR\x06artist\x12\x19\n" +
	"\bother_id\x18\t \x01(\tR\aotherId\x12\x1d\n" +
	"\n" +
	"canvas_uri\x18\v \x01(\tR\tcanvasUri\x1an\n" +
	"\x06Artist\x12\x1d\n" +
	"\n" +
	"artist_uri\x18\x01 \x01(\tR\tartistUri\x12\x1f\n" +
	"\vartist_name\x18\x02 \x01(\tR\n" +
	"artistName\x12$\n" +
	"\x0eartist_img_url\x18\x03 \x01(\tR\fartistImgUrlB'Z%dotfiles/cmds/internal/ewwd/providersb\x06proto3"

var (
	file_internal_ewwd_providers_canvas_proto_rawDescOnce sync.Once
	file_internal_ewwd_providers_canvas_proto_rawDescData []byte
)

func file_internal_ewwd_providers_canvas_proto_rawDescGZIP() []byte {
	file_internal_ewwd_providers_canvas_proto_rawDescOnce.Do(func() {
		file_internal_ewwd_providers_canvas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_ewwd_providers_canvas_proto_rawDesc), len(file_internal_ewwd_providers_canvas_proto_rawDesc)))
	})
	return file_internal_ewwd_providers_canvas_proto_rawDescData
}

var file_internal_ewwd_providers_canvas_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_ewwd_providers_canvas_proto_goTypes = []any{
	(*CanvasRequest)(nil),                // 0: providers.CanvasRequest
	(*CanvasResponse)(nil),               // 1: providers.CanvasResponse
	(*CanvasRequest_Track)(nil),          // 2: providers.CanvasRequest.Track
	(*CanvasResponse_Canvas)(nil),        // 3: providers.CanvasResponse.Canvas
	(*CanvasResponse_Canvas_Artist)(nil), // 4: providers.CanvasResponse.Canvas.Artist
}
var file_internal_ewwd_providers_canvas_proto_depIdxs = []int32{
	2, // 0: providers.CanvasRequest.tracks:type_name -> providers.CanvasRequest.Track
	3, // 1: providers.CanvasResponse.canvases:type_name -> providers.CanvasResponse.Canvas
	4, // 2: providers.CanvasResponse.Canvas.artist:type_name -> providers.CanvasResponse.Canvas.Artist
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_ewwd_providers_canvas_proto_init() }
func file_internal_ewwd_providers_canvas_proto_init() {
	if File_internal_ewwd_providers_canvas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_ewwd_providers_canvas_proto_rawDesc), len(file_internal_ewwd_providers_canvas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_ewwd_providers_canvas_proto_goTypes,
		DependencyIndexes: file_internal_ewwd_providers_canvas_proto_depIdxs,
		MessageInfos:      file_internal_ewwd_providers_canvas_proto_msgTypes,
	}.Build()
	File_internal_ewwd_providers_canvas_proto = out.File
	file_internal_ewwd_providers_canvas_proto_goTypes = nil
	file_internal_ewwd_providers_canvas_proto_depIdxs = nil
}
