[ -f "$HOME/.config/shell/env.sh" ] && source "$HOME/.config/shell/env.sh"

eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

function command_not_found_handler {
    return 127
}

# history
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_FIND_NO_DUPS
setopt SHARE_HISTORY
setopt HIST_REDUCE_BLANKS
setopt AUTO_CD

chpwd() {
    echo
    lsd
}

# aliases
alias niol='clear && source ~/.zshrc'
alias ls='echo; lsd'
alias n='nvim'
alias c='claude'
alias zz='cd ~'
alias m="make"
alias j="just"
alias jt="just test"
alias jr="just req"
alias jw="just watch"
alias s='cd "$(xplr --print-pwd-as-result)"'
alias rh='git reset --soft HEAD^'
alias d='cd ~/dotfiles'
alias D='cd ~/downloads'
alias v='cd ~/vagari'
alias e='cd ~/dotfiles/config/nvim'
alias x='exit'
alias p='paru'
alias k='kaizen'
alias lg='lazygit'
alias ld='lazydocker'
alias uvpn='vpn up'
alias dvpn='vpn down'

alias update='paru -Syu && paru -Rns $(paru -Qdtq) 2>/dev/null; paru -Qq | sort > ~/dotfiles/etc/packages.lst'
alias oc='ouch compress'
alias od='ouch decompress'
alias ol='ouch list --tree'
alias man='man --pager=$PAGER'
function etree () {
    echo
    if [[ -z $1 ]]; then
        L=2
    else
        L=$1
    fi
    erd -L "$L" --suppress-size --threads 16 --layout inverted
}

alias ew='eww-open'
alias ews='eww inspector & disown && exit'
alias el='eww logs'

# plugins
if [[ ! -f ${ZDOTDIR:-${HOME}}/.zcomet/bin/zcomet.zsh ]]; then
    command git clone https://github.com/agkozak/zcomet.git ${ZDOTDIR:-${HOME}}/.zcomet/bin
fi
source ${ZDOTDIR:-${HOME}}/.zcomet/bin/zcomet.zsh

# plugin settings (before loading)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

# plugins (order matters - syntax highlighting must be last)
zcomet load zsh-users/zsh-completions
zcomet load zsh-users/zsh-autosuggestions
zcomet load Aloxaf/fzf-tab
zcomet load zsh-users/zsh-syntax-highlighting

autoload -U compinit; compinit

# fix keys
bindkey -v
export KEYTIMEOUT=01
bindkey '^[[H'     vi-beginning-of-line
bindkey '^[[F'     vi-end-of-line
bindkey '^[[3~'    delete-char
bindkey '^[[1;5C'  forward-word   # C-left
bindkey '^[[1;5D'  backward-word  # C-right
bindkey '^[[1;5A'  history-incremental-search-backward # C-up
bindkey '^[[1;5B'  history-incremental-search-forward  # C-down

eval "$(atuin init zsh)"

source $HOME/.config/zsh/vagari-highlights.zsh
