wireplumber.settings = {
  bluetooth.autoswitch-to-headset-profile = false
}

monitor.bluez.properties = {
  bluez5.roles = [ a2dp_source ]
}

monitor.bluez.rules = [
  {
    matches = [
      {
        api.bluez5.address = "70:F9:4A:C0:E5:2E"
      }
    ]
    actions = {
      update-props = {
        session.dont-restore-off-profile = true
      }
    }
  }
]

monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.*"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  }
]
